server:
  port: 8081

# Eureka server confif
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    
      
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: grocery-delivery-service
  data:
    mongodb:
      host: localhost
      port: 8091
      database: Gorillas
  mongodb:
    embedded:
      version: 4.0.2
  
  graphql:
    path: /grocery/delivery 
    graphiql:
      enabled: true   # for testing on graphiql
      path: /graphiql #context for graphiql 


resilience4j:
    circuitbreaker:
        instances:
            updateDelivery:
                slidingWindowSize: 50
                slidingWindowType: COUNT_BASED
                minimumNumberOfCalls: 50
                failureRateThreshold: 50
                permittedNumberOfCallsInHalfOpenState: 20
                automaticTransitionFromOpenToHalfOpenEnabled: true
                registerHealthIndicator: false
                allowHealthIndicatorToFail: true
                slowCallDurationThreshold: 6000
                slowCallRateThreshold: 50